return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 21,
  height = 21,
  tilewidth = 36,
  tileheight = 36,
  nextlayerid = 4,
  nextobjectid = 64,
  properties = {},
  tilesets = {
    {
      name = "dungeon sei la",
      firstgid = 1,
      filename = "dungeon sei la.tsx",
      tilewidth = 36,
      tileheight = 36,
      spacing = 0,
      margin = 0,
      columns = 7,
      image = "../assets/dungeonTileset.png",
      imagewidth = 252,
      imageheight = 144,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 36,
        height = 36
      },
      properties = {},
      terrains = {},
      tilecount = 28,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 21,
      height = 21,
      id = 1,
      name = "ground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 21,
      height = 21,
      id = 3,
      name = "wallsDrawing",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        9, 1, 2, 2, 2, 2, 2, 2, 2, 2, 24, 2, 2, 2, 2, 2, 2, 2, 2, 3, 9,
        9, 1, 4, 5, 5, 5, 5, 5, 5, 5, 26, 5, 5, 5, 5, 5, 5, 5, 6, 3, 9,
        9, 1, 11, 27, 27, 12, 27, 27, 27, 12, 26, 12, 27, 27, 27, 12, 27, 27, 13, 3, 9,
        9, 1, 11, 12, 12, 12, 12, 12, 12, 12, 26, 12, 12, 12, 12, 12, 12, 12, 13, 3, 9,
        9, 1, 11, 27, 27, 12, 26, 12, 12, 12, 26, 12, 12, 12, 26, 12, 27, 27, 13, 3, 9,
        9, 1, 18, 19, 19, 12, 26, 12, 12, 12, 26, 12, 12, 12, 26, 12, 19, 19, 20, 3, 9,
        9, 15, 25, 25, 23, 11, 21, 27, 27, 12, 26, 12, 27, 27, 14, 13, 22, 16, 16, 17, 9,
        9, 9, 9, 9, 1, 11, 26, 12, 12, 12, 12, 12, 12, 12, 26, 13, 3, 9, 9, 9, 9,
        2, 2, 2, 2, 2, 11, 26, 12, 1, 2, 12, 2, 3, 12, 26, 13, 2, 2, 2, 2, 2,
        12, 12, 12, 12, 12, 12, 12, 12, 1, 18, 19, 20, 3, 12, 12, 12, 12, 12, 12, 12, 12,
        25, 25, 25, 25, 23, 11, 26, 12, 15, 16, 16, 16, 17, 12, 26, 13, 22, 25, 25, 25, 25,
        9, 9, 9, 9, 1, 11, 26, 12, 12, 12, 12, 12, 12, 12, 26, 13, 3, 9, 9, 9, 9,
        9, 1, 2, 2, 2, 11, 26, 12, 2, 2, 7, 2, 2, 12, 26, 13, 2, 2, 2, 3, 9,
        9, 1, 4, 5, 5, 12, 12, 12, 12, 12, 26, 12, 12, 12, 12, 12, 5, 5, 6, 3, 9,
        9, 1, 11, 2, 14, 12, 27, 27, 27, 12, 26, 12, 27, 27, 27, 12, 21, 27, 13, 3, 9,
        9, 1, 11, 12, 26, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 26, 12, 13, 3, 9,
        9, 1, 27, 12, 26, 12, 26, 12, 2, 2, 7, 2, 2, 12, 26, 12, 26, 12, 27, 3, 9,
        9, 1, 11, 12, 12, 12, 26, 12, 12, 12, 26, 12, 12, 12, 26, 12, 12, 12, 13, 3, 9,
        9, 1, 11, 27, 27, 27, 28, 27, 27, 12, 26, 12, 27, 27, 28, 27, 27, 27, 13, 3, 9,
        9, 1, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 13, 3, 9,
        9, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 9
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 108,
          y = 72,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 72,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 108,
          y = 144,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 144,
          width = 36,
          height = 180,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 252,
          y = 216,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 36,
          width = 36,
          height = 216,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 0,
          width = 612,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 0,
          width = 36,
          height = 252,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 216,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 252,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = -36,
          y = 288,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = -36,
          y = 360,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 756,
          y = 288,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 756,
          y = 360,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 396,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 432,
          width = 144,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 468,
          width = 36,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 720,
          width = 612,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 684,
          y = 468,
          width = 36,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 432,
          width = 144,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 360,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 288,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 216,
          width = 144,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 684,
          y = 0,
          width = 36,
          height = 216,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 252,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 396,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 648,
          y = 576,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 504,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 540,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 504,
          y = 576,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 648,
          width = 216,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 576,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 612,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 108,
          y = 648,
          width = 216,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 576,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 576,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 108,
          y = 504,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 540,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 504,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 360,
          width = 36,
          height = 108,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 432,
          width = 180,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 468,
          width = 36,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 504,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 504,
          y = 360,
          width = 36,
          height = 108,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 216,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 504,
          y = 144,
          width = 36,
          height = 180,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 72,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 72,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 144,
          width = 72,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 324,
          y = 288,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 396,
          y = 288,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 288,
          width = 36,
          height = 108,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 36,
          height = 108,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 324,
          y = 360,
          width = 108,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
